---
layout: single
title:  "python"

categories:
  - python
tags:
  - 
  
---
1.13 예외처리
---

### 예외처리

예외란 코드를 실행하는 중에 발생한 프로그램에서 처리 가능한 에러를 뜻한다.

```
형식)
     try:
         실행명령어 1
         실행명령어 2
         실행명령어 3
         ...
    except 오류종류:
         예외처리 명렁 1
         예외처리 명렁 2
         예외처리 명렁 3
         ...
```
```python
def main():
    print('나누기 전용 계산기 입니다.')
    try:
        num1 = int(input('첫 번째 숫자를 입력하세요>'))
        num2 = int(input('두 번째 숫자를 입력하세요>'))

        print('{0}/{1} = {2}'.format(num1,num2,int(num1/num2)))
        # 숫자를 입력 하세요 > 숫자가 아닌 문자를 입력하면
        # ValueError: invalid literal for int() with base 10: 'a'
    except ValueError:
        print('오류 발생! 잘못된 값을 입력 했습니다.')

main()
```

```
형식)
     try:
         실행명령어 1
         실행명령어 2
         실행명령어 3
         ...
    except 오류종류:
         예외처리 명렁 1
         예외처리 명렁 2
         예외처리 명렁 3
         ...
    except 오류종류2 as 변수명:
         예외처리 명렁 1
         예외처리 명렁 2
         예외처리 명렁 3
         ...
```

```
def main():
    print('나누기 전용 계산기 입니다.')
    try:
        num1 = int(input('첫 번째 숫자를 입력하세요>'))
        num2 = int(input('두 번째 숫자를 입력하세요>'))

        print('{0}/{1} = {2}'.format(num1,num2,int(num1/num2)))
        # 숫자를 입력 하세요 > 숫자가 아닌 문자를 입력하면
        # ValueError: invalid literal for int() with base 10: 'a'
    except ValueError:
        print('오류 발생! 잘못된 값을 입력 했습니다.')
    except ZeroDivisionError as err:
        print('ZeroDivisionError',err)
    
    print('프로그램 종료!')


main()
```
```
형식)
     try:
         실행명령어 1
         실행명령어 2
         실행명령어 3
         ...
    except 오류종류:
         예외처리 명렁 1
         예외처리 명렁 2
         예외처리 명렁 3
         ...
    except 오류종류2 as 변수명:
         예외처리 명렁 1
         예외처리 명렁 2
         예외처리 명렁 3
         ...
    except Exception as 변수명:
         예외처리 명렁 1
         예외처리 명렁 2
         예외처리 명렁 3
         ...
```

```python
def main():
    print('나누기 전용 계산기 입니다.')
    try:
        nums = []

        nums.append(int(input('첫 번째 숫자를 입력하세요>')))
        nums.append(int(input('두 번째 숫자를 입력하세요>')))

        nums.append(nums[0]/nums[1])

        print('{0}/{1} = {2}'.format(nums[0],nums[1],nums[2]))
        # 숫자를 입력 하세요 > 숫자가 아닌 문자를 입력하면
        # ValueError: invalid literal for int() with base 10: 'a'
    except ValueError:
        print('오류 발생! 잘못된 값을 입력 했습니다.')
    except ZeroDivisionError as err:
        print('ZeroDivisionError',err)
    except Exception as err:
        print(err)
    print('프로그램 종료!')
main()
```
그외 알지 못하는 모든 예외는 Exception이 담당  

### 예외 처리 클래스 계층 구조

![32](/assets/images/PYTHON/32.PNG)

```html
BaseException
├── SystemExit
├── KeyboardInterrupt
├── GeneratorExit
├── <span style = "color:red">Exception</span>
│   ├── StopIteration
│   ├── ArithmeticError
│   │   ├── FloatingPointError
│   │   ├── OverflowError
│   │   └── ZeroDivisionError
│   ├── AssertionError
│   ├── AttributeError
│   ├── BufferError
│   ├── EOFError
│   ├── ImportError
│   ├── LookupError
│   │   ├── IndexError
│   │   └── KeyError
│   ├── MemoryError
│   ├── NameError
│   │   └── UnboundLocalError
│   ├── OSError
│   │   ├── FileNotFoundError
│   │   ├── PermissionError
│   │   └── ... (기타 운영 체제 관련 예외)
│   ├── ReferenceError
│   ├── RuntimeError
│   │   ├── NotImplementedError
│   │   └── RecursionError
│   ├── SyntaxError
│   ├── IndentationError
│   │   └── TabError
│   ├── SystemError
│   ├── TypeError
│   ├── ValueError
│   │   └── ... (기타 값 관련 예외)
│   └── ... (기타 예외)
└── <span style = "color:red">Warning</span>
    ├── DeprecationWarning
    ├── PendingDeprecationWarning
    ├── RuntimeWarning
    ├── SyntaxWarning
    ├── UserWarning
    ├── FutureWarning
    ├── ImportWarning
    ├── UnicodeWarning
    └── ... (기타 경고)
```

### 오류와 상관없이 무조건 실행하기 : finally

예외 발생 유무와 상관 없이 무조건 수행!  
```
구문)
     f = open("pcwk.txt","w")
     try:
          수행 코드1
          수행 코드2
          수행 코드3
     finally:
          f.close()
          무조건 수행코드2
          무조건 수행코드3

     try:
         실행명령어 1
         실행명령어 2
         실행명령어 3
         ...
    except 오류종류:
         예외처리 명렁 1
         예외처리 명렁 2
         예외처리 명렁 3
         ...
    except 오류종류2 as 변수명:
         예외처리 명렁 1
         예외처리 명렁 2
         예외처리 명렁 3
         ...
    finally:
         무조건 수행코드1
         무조건 수행코드2
```

```python
def main():
    print('나누기 전용 계산기 입니다.')
    try:
        nums = []
        nums.append(int(input('첫 번째 숫자를 입력하세요>')))
        nums.append(int(input('두 번째 숫자를 입력하세요>')))

        nums.append(nums[0]/nums[1])

        print('{0}/{1} = {2}'.format(nums[0],nums[1],nums[2]))
        # 숫자를 입력 하세요 > 숫자가 아닌 문자를 입력하면
        # ValueError: invalid literal for int() with base 10: 'a'
    except ValueError:
        print('오류 발생! 잘못된 값을 입력 했습니다.')
    except ZeroDivisionError as err:
        print('ZeroDivisionError',err)
    except Exception as err:
        print(err)
    finally:  #자원반납, 파일open, close, 데이터 베이스 연결,종료
        print('계산기를 사용해 주셔서 감사합니다.')
    print('프로그램 종료!')


main()

```
### 오류 발생시키기

의도적으로 오류를 발생  
```
형식)
    raise 오류 종류

```
```python
def main():
    print('나누기 전용 계산기 입니다.')
    try:
        num1 = (int(input('첫 번째 숫자를 입력하세요>')))
        num2 = (int(input('두 번째 숫자를 입력하세요>')))

        if num1 >= 10 or num2 >=10: #입력 받은 숫자가 2자리 이면
            raise ValueError # 예외 발생

        print('{0}/{1}={2}'.format(num1,num2,int(num1/num2)))
        # 숫자를 입력 하세요 > 숫자가 아닌 문자를 입력하면
        # ValueError: invalid literal for int() with base 10: 'a'
    except ValueError as err:
        print('오류 발생! 잘못된 값을 입력 했습니다.')
    except ZeroDivisionError as err:
        print('ZeroDivisionError',err)
    finally:  #자원반납, 파일open, close, 데이터 베이스 연결,종료
        print('계산기를 사용해 주셔서 감사합니다.')

    print('프로그램 종료!')
    
main()

```

### 사용자 정의 예외 처리하기

```python
class BigNumberError(Exception): #사용자 정의 예외, Exception 상속
    pass

#계산기 프로그램

def main():
    print('나누기 전용 계산기 입니다.')
    try:
        num1 = int(input('첫 번째 숫자를 입력하세요>'))
        num2 = int(input('두 번째 숫자를 입력하세요>'))

        if num1 >= 10 or num2 >=10: #입력 받은 숫자가 2자리 이면
            raise ValueError # 예외 발생

        print('{0}/{1}={2}'.format(num1,num2,int(num1/num2)))
        # 숫자를 입력 하세요 > 숫자가 아닌 문자를 입력하면
        # ValueError: invalid literal for int() with base 10: 'a'
    except ValueError as err:
        print('오류 발생! 잘못된 값을 입력 했습니다.')
    except ZeroDivisionError as err:
        print('ZeroDivisionError',err)
    except BigNumberError as err:
        print('BigNumberError',err)
    finally:  #자원반납, 파일open, close, 데이터 베이스 연결,종료
        print('계산기를 사용해 주셔서 감사합니다.')

    print('프로그램 종료!')
    
main()
```


### 큰 숫자 에러 예외 처리하기

```python
class BigNumberError(Exception): #사용자 정이 예외, Exception 상속
    def __init__(self,msg): # 스페셜 메서드, 던더 메서드(dunder method)
        self.msg = msg

    def __str__(self):
        return '[오류 코드 : 001]'+self.msg #메시지 가공

#계산기 프로그램

def main():
    print('나누기 전용 계산기 입니다.')
    try:
        num1 = int(input('첫 번째 숫자를 입력하세요>'))
        num2 = int(input('두 번째 숫자를 입력하세요>'))

        if num1 >= 10 or num2 >=10: #입력 받은 숫자가 2자리 이면
            raise BigNumberError('입력값:{0}, {1}'.format(num1,num2)) # 예외 발생

        print('{0}/{1}={2}'.format(num1,num2,int(num1/num2)))
        # 숫자를 입력 하세요 > 숫자가 아닌 문자를 입력하면
        # ValueError: invalid literal for int() with base 10: 'a'
    except ValueError as err:
        print('오류 발생! 잘못된 값을 입력 했습니다.')
    except ZeroDivisionError as err:
        print('ZeroDivisionError',err)
    except BigNumberError as err:
        print('BigNumberError',err)
    finally:  #자원반납, 파일open, close, 데이터 베이스 연결,종료
        print('계산기를 사용해 주셔서 감사합니다.')

    print('프로그램 종료!')
    
main()

```

![33](/assets/images/PYTHON/33.PNG)
![34](/assets/images/PYTHON/34.PNG)

```python
class BigNumberError(Exception): #사용자 정의 예외, Exception 상속
    def __init__(self,msg): # 스페셜 메서드, 던더 메서드(dunder method)
        self.msg = msg

    def __str__(self):
        return '[오류 코드 : 001]'+self.msg #메시지 가공
class SoldOutError(Exception): #사용자 정의 예외, Exception 상속
    def __init__(self,msg): # 스페셜 메서드, 던더 메서드(dunder method)
        self.msg = msg

    def __str__(self):
        return '[오류 코드 : 001]'+self.msg #메시지 가공
def main():
    chicken = 10 # 남은 치킨 수
    waiting = 1 # 대기번호, 1부터 시작

    while True:
        print("[남은 치킨 : {0}".format(chicken))

        try:
            order = int(input("치킨을 몇 마리 주문 하시겠습니까?"))
            if order < 0:
                raise ValueError('작어.')  # 예외 발생
            if order > 10 :
                raise BigNumberError('{0}을 넘었어요!'.format(order))  # 예외 발생
            if order > chicken:
                raise SoldOutError('soldout!')
        except ValueError as err:
            print('값을 잘못 입력했습니다.')
            break
        except BigNumberError as err:
            print('BigNumberError', err)
            break
        except SoldOutError as err:
            print('BigNumberError', err)
            break

        if order > chicken: # 남은 치킨보다 주문량이 많을 때
            print('재료가 부족합니다.')
        else:
            print("[대기번호 {0}] {1}마리를 주문했습니다.".format(waiting,order))
            waiting += 1 # 대기번호 1 증가
            chicken -= order # 주문 수만큼 치킨 감소

main()
```


#### 사용자 정의 예외

1. 파이썬에 제공하는 오류 외에 사용자가 직접 오류를 정의해 예외 처리를 할 수 있다.
2. 모든 예외의 조상에 해당되는 Exception클래스를 상속 한다.

#### finally

finally문은 try문에서 오류 발생 여부와 무관하게 try문을 벗어 나는 시점에 항상 수행  
finally문은 try와 except문 가장 밑에 정의 한다.

그외
```
   try:
      # 예외가 발생할 수 있는 코드 블록
      result = some_function()
   except SomeException as e:
      #예외가 발생 했을 때 처리할 코드 블록
      print("An exception occureed",e)
  else:
      #예외가 발생하지 않았을 때 실행될 코드 블록
      print("No exception occurred.")
  finally:
      #예외 발생 여부와 관계없이 항상 실행되는 코드 블록
      print("Finally block executed.")

```

![35](/assets/images/PYTHON/35.PNG)

```python
def save_battery(level):
    print('{0}남았으'.format(level))

def main():
    try:
        level = int(input("배터리 몇 프로여?"))
        if level > 30 and level <= 100:
            save_battery(level)
            print('일반 모드')
        if level > 5 and level < 30:
            save_battery(level)
            print('절전 모드')
        if level <= 5:
            raise Exception('종료')  # 예외 발생
    except Exception as err:
        print(err)

main()

```









